[EDITORS-250] Improve filter for tree editors for UsageModel, SEFF and Assembly Diagrams
PalladioSimulator/Palladio-Editors-Commons pull request #10
Opened 2021-10-22 06:35 UTC by Yabbies

2021-11-26 06:33 UTC, sdkrach requested changes
In principle the changes look good to me. Some minor remarks you find inline.

Furthermore: Please check your source code style settings. There is a mixture of space and tab indentation. Please check the indentation as well. Please use the coding conventions from our github repository (https://github.com/PalladioSimulator/Palladio-Build-CodingConventions)

2021-11-26 06:33 UTC, sdkrach commented on bundles/org.palladiosimulator.pcm.edit/src/org/palladiosimulator/pcm/seff/provider/AbstractActionItemProvider.java
> +            			.filter(Predicate.not(StartAction.class::isInstance)) //EMF Package verwenden.
As you commented already, use the SeffPackage.Literals.START_ACTION.isInstance method

2021-11-26 06:33 UTC, sdkrach commented on bundles/org.palladiosimulator.pcm.edit/src/org/palladiosimulator/pcm/seff/provider/AbstractActionItemProvider.java
> +            			.filter(Predicate.not(StopAction.class::isInstance))
same here.

2021-11-26 06:33 UTC, sdkrach commented on bundles/org.palladiosimulator.pcm.edit/src/org/palladiosimulator/pcm/seff/provider/StartActionItemProvider.java
> +		});
Move to either class or static utility method (e.g. createEmptyValueChoiceCalculator) to make things clear and reuse it for the StopAction.

2021-11-26 06:33 UTC, sdkrach commented on bundles/org.palladiosimulator.pcm.edit/src/org/palladiosimulator/pcm/seff/provider/StopActionItemProvider.java
> +		});
Reuse from above

2021-11-26 06:33 UTC, sdkrach commented on bundles/org.palladiosimulator.pcm.edit/src/org/palladiosimulator/pcm/core/composition/provider/AssemblyConnectorItemProvider.java
> +            		contexts.addAll(contexts2);
Please fix the indentation. It got me confused (contexts.clear could actually override the model field if providingContext were null).

2021-11-26 06:33 UTC, sdkrach commented on bundles/org.palladiosimulator.pcm.edit/src/org/palladiosimulator/pcm/core/composition/provider/AssemblyConnectorItemProvider.java
> +				// Für Filterschritte private Methoden bauen die predicates zurückggeben, jenachdem welcher Filter bruacht.
TODO comments should start with /TODO as they are separately highlighted by most IDEs. Remove if you don't feel they are necessary anymore.

2021-11-26 06:33 UTC, sdkrach commented on bundles/org.palladiosimulator.pcm.edit/src/org/palladiosimulator/pcm/core/composition/provider/AssemblyConnectorItemProvider.java
> +            		//Schmeiße alle Contexte raus, die keinen Match mit der requiringContextInterfaces Liste haben:
Please translate your comments into english.

2021-11-26 06:33 UTC, sdkrach commented on bundles/org.palladiosimulator.pcm.edit/src/org/palladiosimulator/pcm/core/composition/provider/AssemblyConnectorItemProvider.java
> +	private List<AssemblyContext> removeContext(Collection<AssemblyContext> contexts, AssemblyConnector connector, RequiringProviding flag) {
This method name is rather confusing. You do not remove the context from the underlying list, but return a copy without it. I would rather go for excludeContext or getCopyWithoutContext

2021-11-26 06:33 UTC, sdkrach commented on bundles/org.palladiosimulator.pcm.edit/src/org/palladiosimulator/pcm/core/composition/provider/AssemblyConnectorItemProvider.java
> +	private Predicate<AssemblyContext> contextProvidingRolesAssignableFromRole(AssemblyConnector connector, RequiringProviding flag) {
In general, although these are private methods, could you provide some short Java-Doc commentary stating what kind of filter is created by the method?

2021-11-26 06:33 UTC, sdkrach commented on bundles/org.palladiosimulator.pcm.edit/src/org/palladiosimulator/pcm/core/composition/provider/AssemblyConnectorItemProvider.java
> +	private Predicate<AssemblyContext> contextRequiringRolesAssignableFromRole(AssemblyConnector connector, RequiringProviding flag) {
same here.

2021-11-26 06:33 UTC, sdkrach commented on bundles/org.palladiosimulator.pcm.edit/src/org/palladiosimulator/pcm/usagemodel/provider/StartItemProvider.java
> +	}
same here

2021-11-26 06:33 UTC, sdkrach commented on bundles/org.palladiosimulator.pcm.edit/src/org/palladiosimulator/pcm/usagemodel/provider/StopItemProvider.java
> +	}
same here

2021-11-26 06:33 UTC, sdkrach commented on tests/org.palladiosimulator.pcm.edit.tests/src/org/palladiosimulator/pcm/edit/provider/TestItemProviderUtilities.java
> +                .createURI("testmodels/MediaStore-InstantDownloadCache.system"), true);
You should put these hard-coded strings into Constants at the top of the class. Or create a constructor which allows you to reuse these utilities by providing a foldername, you can instantiate it to an attribute in your test, giving the concrete folder name)

2022-06-10 07:54 UTC, rapp-fzi approved these changes
temporal approve to trigger build pipeline

2022-06-10 08:10 UTC, Nicolas-Boltz submitted a review, later dismissed
All comments fixed

2022-06-13 08:04 UTC, rapp-fzi commented
Closed this  PR due to migration to new build environment. PR will be re-submitted

2022-06-13 08:04 UTC, closed without merging